[build]
command = "chmod +x ./mvnw && ./mvnw clean site"
publish = "/target"  # Adjust to your actual publish directory

[context.production.environment]
MONGO_DATABASE="manga-db"
MONGO_USER="pavanpinninti"
MONGO_PASSWORD="16122114pP"
MONGO_CLUSTER="cluster0.lecukr8.mongodb.net"
JAVA_VERSION = "17"

